### ISSUE TITLE
Need a roadmap

### ISSUE THREAD

**Issue by kfihihc** [makerdiary/nrf52-u2f#1]
- [ ] Compatible with more websites/apps
  - [ ] [Dropbox](https://www.dropbox.com/help/security/enable-two-step-verification)
  - [x] [Stripe](https://support.stripe.com/questions/authentication-using-fido-u2f-security-keys)
  - [ ] [Bitbucket](https://bitbucket.org/blog/universal-2nd-factor)
  - [ ] [FastMail](https://www.fastmail.com/help/account/2fa.html)
  - [ ] [Vultr](https://www.vultr.com/docs/using-two-factor-authentication-to-login-to-vultr-control-panel)
- [ ] Bluetooth Low Energy support for U2F
- [ ] NFC support
- [ ] Compatible with FIDO2

**Comment by touchjet** [comment]
Is there any chance having the BLE U2F implementation soon?

**Comment by caizelin** [comment]
> Is there any chance having the BLE U2F implementation soon?

BLE U2F is working in progress. It may come with the next release.
